modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="http://github.com/bl4ckscor3/GetItTogetherDrops/issues"
license="MIT License http://github.com/bl4ckscor3/GetItTogetherDrops/blob/1.16/LICENSE"

[[mods]] 
	modId="getittogetherdrops"
	version="v1.0"
	displayName="Get It Together, Drops!"
	displayURL="http://minecraft.curseforge.com/projects/get-it-together-drops"
	authors="bl4ckscor3"
	description='''Adds configuration options for defining how dropped items should combine.'''

[[dependencies.getittogetherdrops]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.getittogetherdrops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17]"
    ordering="NONE"
    side="BOTH"
